import { ImageResponse } from 'next/og';
import { getAllListingSlugs, getListingBySlug } from '@/lib/listings';

export const size = { width: 1200, height: 630 };
export const contentType = 'image/png';
export const alt = 'Listing in the Integrity Framework Directory';

// Note: do NOT export generateStaticParams here. Next.js's metadata-route
// loader auto-derives it from generateImageMetadata; defining it explicitly
// causes a "Duplicate export 'generateStaticParams'" build error. Slugs come
// from the parent /listings/[slug]/page.tsx generateStaticParams instead.

export async function generateImageMetadata({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const listing = getListingBySlug(slug);
  if (!listing) return [];
  return [
    {
      id: 'default',
      contentType,
      size,
      alt: `${listing.name} — ${listing.tier} tier in the Integrity Framework Directory`,
    },
  ];
}

// Reference getAllListingSlugs to keep the import live for Next's static analysis;
// the actual slug list is generated by the parent page.tsx.
void getAllListingSlugs;

const TIER_FILL: Record<'bronze' | 'silver', string> = {
  bronze: '#b87333',
  silver: '#a3afbd',
};

const TIER_RING: Record<'bronze' | 'silver', string> = {
  bronze: '#fdf6ee',
  silver: '#f5f7f9',
};

const TIER_INK: Record<'bronze' | 'silver', string> = {
  bronze: '#7c4b22',
  silver: '#374049',
};

export default async function OG({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const listing = getListingBySlug(slug);

  if (!listing) {
    return new ImageResponse(
      (
        <div
          style={{
            width: '100%',
            height: '100%',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            background: '#1e293b',
            color: '#f1f5f9',
            fontSize: 36,
          }}
        >
          Listing not found
        </div>
      ),
      { ...size },
    );
  }

  const fill = TIER_FILL[listing.tier];
  const ring = TIER_RING[listing.tier];
  const ink = TIER_INK[listing.tier];

  return new ImageResponse(
    (
      <div
        style={{
          width: '100%',
          height: '100%',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'space-between',
          padding: '72px',
          background: '#ffffff',
          color: '#0f172a',
          fontFamily:
            'ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial',
        }}
      >
        <div
          style={{
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            color: '#475569',
            fontSize: 18,
            letterSpacing: 4,
            textTransform: 'uppercase',
            fontWeight: 600,
          }}
        >
          <span>theintegrityframework.org</span>
          <span
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: 12,
              padding: '10px 20px',
              borderRadius: 999,
              background: ring,
              color: ink,
              border: `1px solid ${fill}33`,
              letterSpacing: 2,
              fontSize: 16,
            }}
          >
            <span
              style={{
                display: 'flex',
                width: 12,
                height: 12,
                borderRadius: 999,
                background: fill,
              }}
            />
            {listing.tier.toUpperCase()}
          </span>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: 12,
              fontSize: 80,
              fontWeight: 700,
              lineHeight: 1.05,
              color: '#0f172a',
              maxWidth: 1080,
            }}
          >
            {listing.name}
            {listing.operator.isDirectoryOperator && (
              <span
                style={{
                  display: 'flex',
                  fontSize: 56,
                  color: '#475569',
                  marginLeft: 4,
                }}
              >
                *
              </span>
            )}
          </div>
          <div
            style={{
              display: 'flex',
              fontSize: 26,
              color: '#475569',
              maxWidth: 1080,
              lineHeight: 1.4,
            }}
          >
            {listing.description}
          </div>
        </div>

        <div
          style={{
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            color: '#64748b',
            fontSize: 18,
          }}
        >
          <div style={{ display: 'flex', gap: 32 }}>
            <span style={{ display: 'flex' }}>{listing.operator.name}</span>
            {listing.category && (
              <span
                style={{
                  display: 'flex',
                  color: '#94a3b8',
                  textTransform: 'uppercase',
                  letterSpacing: 2,
                  fontSize: 14,
                  alignItems: 'center',
                }}
              >
                {listing.category}
              </span>
            )}
          </div>
          <div style={{ display: 'flex' }}>Last re-scanned {listing.lastRescannedDate}</div>
        </div>
      </div>
    ),
    { ...size },
  );
}
